---
- name: start VM 
  hosts: localhost
  vars_files: vars.yml
  become: false
  gather_facts: false
  collections:
    - community.vmware

  tasks:
  - name: deploy VM
    local_action:
      module: vmware_guest
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      datacenter: Datacenter
      datastore: datastore_6TB
      folder: centos
      template: "{{item.template}}"
      name: "{{item.name}}"
      hardware:
        nested_virt: true
        memory_mb: "{{item.memory_mb}}"
      networks:
        - name: VMs11
          ip: "{{item.ip}}"
          netmask: "255.255.255.0"
          gateway: "10.100.11.254"
      customization:
        hostname: "{{item.hostname}}"
        dns_servers: [8.8.8.8]
      state: powered-on
      wait_for_ip_address: true
    with_items: "{{servers}}"
    register: deploy
    delegate_to: localhost
    tags:
    - install

- name: web
  hosts: centos_web
  become: true 
  gather_facts: false
  tasks:
  - name: copy conf files
    copy:
      src: "{{item}}"
      dest: /etc/rsyslog.d/
    with_items:
      - 10-nginx.conf
      - 20-crit.conf
      - 30-audit.conf
      
  - name: install web rsyslog
    shell: "{{item}}"
    with_items:
      - setenforce 0
      - sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config
      - firewall-cmd --permanent --add-port=80/tcp
      - firewall-cmd --reload
      - yum install -y nginx
      - sed -i '/error_log/a error_log syslog:server=10.100.11.112:514,tag=nginx_error;' /etc/nginx/nginx.conf 
      - sed -i '/access_log/a access_log syslog:server=10.100.11.112:514,tag=nginx_access,severity=info;' /etc/nginx/nginx.conf
      - systemctl start nginx
      - systemctl enable nginx
      - systemctl restart rsyslog
  tags:
  - web
 
- name: log
  hosts: centos_log
  become: true 
  gather_facts: false
  tasks:
  - name: install log
    shell: "{{item}}"
    with_items:
      - firewall-cmd --permanent --add-port=514/tcp --permanent --add-port=514/udp
      - firewall-cmd --reload
      - sed -i 's/#input/input/g' /etc/rsyslog.conf
      - sed -i 's/#module(load="imudp/module(load="imudp/' /etc/rsyslog.conf
      - sed -i 's/#module(load="imtcp/module(load="imtcp/' /etc/rsyslog.conf
      - echo "\$template RemoteLogs,\"/var/log/rsyslog/%HOSTNAME%/%PROGRAMNAME%.log\"" >> /etc/rsyslog.conf
      - echo "*.* ?RemoteLogs" >> /etc/rsyslog.conf
      - echo "& ~" >> /etc/rsyslog.conf     
      - systemctl restart rsyslog
  tags:
  - log

- name: elk
  hosts: ubuntu_elk
  become: true 
  gather_facts: false
  tasks:
  
  - name: copy files
    copy:
      src: "{{item}}"
      dest: /root/
    with_items:
      - elasticsearch-8.9.2-amd64.deb
      - logstash-8.9.2-amd64.deb
      - kibana-8.9.2-amd64.deb
      - filter.conf
      - input.conf
      - output.conf

  - name: install elk
    shell: "{{item}}"
    with_items:
      - iptables -I INPUT -p tcp --dport 5044 -j ACCEPT
      - iptables -I INPUT -p tcp --dport 5601 -j ACCEPT
      - iptables-save -f /etc/iptables/rules.ipv4
      - apt install -y default-jdk

  tags:
  - elk
